apiVersion: v1
data:
  default.conf: "server {\r\n    listen 80;\r\n    server_name localhost;\r\n    root
    /var/www/html;\r\n    index index.php index.html;\r\n    \r\n    location / {\r\n
    \       try_files $uri $uri/ =404;\r\n    }\r\n\r\n    location ~ \\.php$ {\r\n
    \       include fastcgi_params;\r\n        fastcgi_pass localhost:9000;\r\n        fastcgi_index
    index.php;\r\n        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;\r\n
    \   }\r\n}\r\n"
kind: ConfigMap
metadata:
  name: nginx-config
 
