apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-vol
          mountPath: /etc/nginx/conf.d
        - name: data
          mountPath: /var/www/html
      - name: php
        image: dockersiri194/siriphp-app:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /var/www/html
      - name: mysqldb
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: testdb
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql
      volumes:
      - name: mysql
        emptyDir: {}
      - name: config-vol
        configMap:
          name: nginx-config
          items:
          - key: default.conf
            path: default.conf
      - name: data
        emptyDir: {}
